baseurl = "http://pgbr.postgresql.org.br/"
title = "#PGBR2017"
languageCode = "en-us"
contentdir = "app/content"
datadir = "app/data"
layoutdir = "app/layouts"
publishdir = "dist"
staticdir = "app/static"
themesdir = "app/themes"

[params]
  description = "ConferÃªncia Brasileira de PostgreSQL"
  author = "Nikola Tesla"